import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


file1 = r"C:\server_data\Datacenter Datas\SERVER WISE DATA\host_metrics_host1.csv"
file2 = r"C:\server_data\Datacenter Datas\SERVER WISE DATA\host_metrics_host2.csv"
file3 = r"C:\server_data\Datacenter Datas\SERVER WISE DATA\host_metrics_host3.csv"


#Cleaning of data 
def cleaning(file_path):
    data = pd.read_csv(file_path)

    data.drop(columns={"host_id", "cpu_usage_pct", "status", "power_kw"}, inplace=True, errors='ignore')

    df = data[['ts', 'memory_usage_pct']].copy()
    df['ts'] = pd.to_datetime(df['ts'], format='mixed', utc=True).dt.tz_localize(None)

    df.sort_values(by='ts', inplace=True)

    return df

#visualization

def visualization(df):
    sns.lineplot(data=df, x=df['ts'], y=df['memory_usage_pct'], color='blue')
    # sns.jointplot(data=df, x=df['ts'], y=df['memory_usage_pct'],color='blue')
    plt.title("visualization of memory utilization for the server")
    plt.tight_layout()
    plt.show()



for i in [file1, file2, file3] :
    df = cleaning(i)
    visualization(df)

def visualize_featured_data(file_path):
    try:
        df = pd.read_csv(file_path)
        df['ts'] = pd.to_datetime(df['ts'], format='mixed')
        
        fig, axes = plt.subplots(3, 1, figsize=(12, 15), sharex=True)
        
        # Plot 1: Memory Usage & Rolling Means
        sns.lineplot(data=df, x='ts', y='memory_usage_pct', label='Original', ax=axes[0], alpha=0.5, color='green')
        sns.lineplot(data=df, x='ts', y='rolling_mean_1h', label='1h Mean', ax=axes[0], color='blue')
        sns.lineplot(data=df, x='ts', y='rolling_mean_24h', label='24h Mean', ax=axes[0], color='red')
        axes[0].set_title('Memory Usage and Rolling Means')
        axes[0].set_ylabel('Memory Usage (%)')
        
        # Plot 2: Rolling Std Devs
        sns.lineplot(data=df, x='ts', y='rolling_std_1h', label='1h Std', ax=axes[1], color='orange')
        sns.lineplot(data=df, x='ts', y='rolling_std_24h', label='24h Std', ax=axes[1], color='purple')
        axes[1].set_title('Rolling Standard Deviations')
        axes[1].set_ylabel('Std Dev')
        
        # Plot 3: Growth Rate & Acceleration
        sns.lineplot(data=df, x='ts', y='growth_rate', label='Growth Rate', ax=axes[2], color='green', alpha=0.7)
        sns.lineplot(data=df, x='ts', y='acceleration', label='Acceleration', ax=axes[2], color='brown', alpha=0.7)
        axes[2].set_title('Growth Rate and Acceleration')
        axes[2].set_ylabel('Rate')
        
        plt.tight_layout()
        plt.show()
    except FileNotFoundError:
        print(f"File {file_path} not found. Please ensure it is generated by feat_eng.py first.")

# Visualize the output data generated by feat_eng.py
visualize_featured_data('out.csv')
visualize_featured_data('out1.csv')
visualize_featured_data('out2.csv')